/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonRaspberryPiPicoW.description': 'A wireless variant of the Raspberry Pi Pico with onboard Wi-Fi and Bluetooth.',
            'microPythonRaspberryPiPicoW.examples.blink.name': 'Blink',
            'microPythonRaspberryPiPicoW.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonRaspberryPiPicoW.examples.button.name': 'Button',
            'microPythonRaspberryPiPicoW.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonRaspberryPiPicoW.examples.fade.name': 'Fade',
            'microPythonRaspberryPiPicoW.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonRaspberryPiPicoW.examples.knob.name': 'Knob',
            'microPythonRaspberryPiPicoW.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonRaspberryPiPicoW.examples.servoSweep.name': 'Servo Sweep',
            'microPythonRaspberryPiPicoW.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonRaspberryPiPicoW.examples.consolePrint.name': 'Console Print',
            'microPythonRaspberryPiPicoW.examples.consolePrint.description': 'Print messages to the terminal.'
        },
        'ru': {
            'microPythonRaspberryPiPicoW.description': 'Беспроводной вариант Raspberry Pi Pico со встроенными Wi-Fi и Bluetooth.',
            'microPythonRaspberryPiPicoW.examples.blink.name': 'Мигание',
            'microPythonRaspberryPiPicoW.examples.blink.description': 'Заставьте встроенный светодиод мигать.',
            'microPythonRaspberryPiPicoW.examples.button.name': 'Кнопка',
            'microPythonRaspberryPiPicoW.examples.button.description': 'Зажигайте светодиод, пока нажата кнопка.',
            'microPythonRaspberryPiPicoW.examples.fade.name': 'Плавное затухание',
            'microPythonRaspberryPiPicoW.examples.fade.description': 'Плавное затухание светодиода с помощью ШИМ.',
            'microPythonRaspberryPiPicoW.examples.knob.name': 'Регулятор',
            'microPythonRaspberryPiPicoW.examples.knob.description': 'Регулировка яркости светодиода с помощью потенциометра.',
            'microPythonRaspberryPiPicoW.examples.servoSweep.name': 'Развертка серво',
            'microPythonRaspberryPiPicoW.examples.servoSweep.description': 'Поворот серво вперед и назад между 0° и 180°.',
            'microPythonRaspberryPiPicoW.examples.consolePrint.name': 'Печать в консоль',
            'microPythonRaspberryPiPicoW.examples.consolePrint.description': 'Печать сообщений в терминал.'
        },
        'zh-cn': {
            'microPythonRaspberryPiPicoW.description': '带板载 Wi-Fi 和蓝牙的无线版 Raspberry Pi Pico。',
            'microPythonRaspberryPiPicoW.examples.blink.name': '闪烁',
            'microPythonRaspberryPiPicoW.examples.blink.description': '让板载 LED 闪烁。',
            'microPythonRaspberryPiPicoW.examples.button.name': '按键',
            'microPythonRaspberryPiPicoW.examples.button.description': '按住按键时点亮 LED。',
            'microPythonRaspberryPiPicoW.examples.fade.name': '呼吸灯',
            'microPythonRaspberryPiPicoW.examples.fade.description': '用 PWM 让 LED 缓缓变亮再渐渐变暗。',
            'microPythonRaspberryPiPicoW.examples.knob.name': '电位器调光',
            'microPythonRaspberryPiPicoW.examples.knob.description': '用电位器调节 LED 的亮度。',
            'microPythonRaspberryPiPicoW.examples.servoSweep.name': '舵机来回扫描',
            'microPythonRaspberryPiPicoW.examples.servoSweep.description': '让舵机在 0° 到 180° 之间来回转动。',
            'microPythonRaspberryPiPicoW.examples.consolePrint.name': '控制台输出',
            'microPythonRaspberryPiPicoW.examples.consolePrint.description': '把消息打印到终端。'
        },
        'zh-tw': {
            'microPythonRaspberryPiPicoW.description': '帶板載 Wi-Fi 和藍牙的無線版 Raspberry Pi Pico。',
            'microPythonRaspberryPiPicoW.examples.blink.name': '閃爍',
            'microPythonRaspberryPiPicoW.examples.blink.description': '讓板載 LED 閃爍。',
            'microPythonRaspberryPiPicoW.examples.button.name': '按鍵',
            'microPythonRaspberryPiPicoW.examples.button.description': '按住按鍵時點亮 LED。',
            'microPythonRaspberryPiPicoW.examples.fade.name': '呼吸燈',
            'microPythonRaspberryPiPicoW.examples.fade.description': '用 PWM 讓 LED 緩緩變亮再漸漸變暗。',
            'microPythonRaspberryPiPicoW.examples.knob.name': '電位器調光',
            'microPythonRaspberryPiPicoW.examples.knob.description': '用電位器調節 LED 的亮度。',
            'microPythonRaspberryPiPicoW.examples.servoSweep.name': '舵機來回掃描',
            'microPythonRaspberryPiPicoW.examples.servoSweep.description': '讓舵機在 0° 到 180° 之間來回轉動。',
            'microPythonRaspberryPiPicoW.examples.consolePrint.name': '終端輸出',
            'microPythonRaspberryPiPicoW.examples.consolePrint.description': '將訊息列印到終端。'
        }
    },
    'extensions': {
        'en': {
            'microPythonRaspberryPiPicoW.modeMenu.input': 'input',
            'microPythonRaspberryPiPicoW.modeMenu.output': 'output',
            'microPythonRaspberryPiPicoW.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPicoW.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPicoW.levelMenu.high': 'high',
            'microPythonRaspberryPiPicoW.levelMenu.low': 'low',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPicoW.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPicoW.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPicoW.category.pins': 'Pins',
            'microPythonRaspberryPiPicoW.category.serial': 'Serial',
            'microPythonRaspberryPiPicoW.category.console': 'Console',
            'microPythonRaspberryPiPicoW.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPicoW.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPicoW.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPicoW.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPicoW.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPicoW.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPicoW.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPicoW.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPicoW.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPicoW.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPicoW.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPicoW.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonRaspberryPiPicoW.modeMenu.input': 'input',
            'microPythonRaspberryPiPicoW.modeMenu.output': 'output',
            'microPythonRaspberryPiPicoW.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPicoW.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPicoW.levelMenu.high': 'high',
            'microPythonRaspberryPiPicoW.levelMenu.low': 'low',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPicoW.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPicoW.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPicoW.category.pins': 'Pins',
            'microPythonRaspberryPiPicoW.category.serial': 'Serial',
            'microPythonRaspberryPiPicoW.category.console': 'Console',
            'microPythonRaspberryPiPicoW.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPicoW.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPicoW.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPicoW.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPicoW.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPicoW.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPicoW.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPicoW.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPicoW.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPicoW.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPicoW.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPicoW.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonRaspberryPiPicoW.modeMenu.input': '输入',
            'microPythonRaspberryPiPicoW.modeMenu.output': '输出',
            'microPythonRaspberryPiPicoW.modeMenu.inputPullup': '上拉输入',
            'microPythonRaspberryPiPicoW.modeMenu.inputPulldown': '下拉输入',
            'microPythonRaspberryPiPicoW.levelMenu.high': '高',
            'microPythonRaspberryPiPicoW.levelMenu.low': '低',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonRaspberryPiPicoW.eolMenu.warp': '换行',
            'microPythonRaspberryPiPicoW.eolMenu.noWarp': '不换行',
            'microPythonRaspberryPiPicoW.category.pins': '引脚',
            'microPythonRaspberryPiPicoW.category.serial': '串口',
            'microPythonRaspberryPiPicoW.category.console': '控制台',
            'microPythonRaspberryPiPicoW.pins.setPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonRaspberryPiPicoW.pins.setDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonRaspberryPiPicoW.pins.setPwmOutput': '设置 PWM 引脚 [PIN] 输出为 [OUT]',
            'microPythonRaspberryPiPicoW.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'microPythonRaspberryPiPicoW.pins.readAnalogPin': '读取模拟引脚 [PIN]',
            'microPythonRaspberryPiPicoW.pins.setServoOutput': '设置舵机引脚 [PIN] 输出为 [OUT]',
            'microPythonRaspberryPiPicoW.pins.attachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonRaspberryPiPicoW.serial.serialBegin': '串口 [NO] 初始化 波特率 [BAUD] 引脚 RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPicoW.serial.multiSerialPrint': '串口 [NO] 打印 [VALUE] [EOL]',
            'microPythonRaspberryPiPicoW.serial.multiSerialReadALine': '串口 [NO] 读取一行',
            'microPythonRaspberryPiPicoW.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonRaspberryPiPicoW.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonRaspberryPiPicoW.modeMenu.input': '輸入',
            'microPythonRaspberryPiPicoW.modeMenu.output': '輸出',
            'microPythonRaspberryPiPicoW.modeMenu.inputPullup': '上拉輸入',
            'microPythonRaspberryPiPicoW.modeMenu.inputPulldown': '下拉輸入',
            'microPythonRaspberryPiPicoW.levelMenu.high': '高',
            'microPythonRaspberryPiPicoW.levelMenu.low': '低',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonRaspberryPiPicoW.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonRaspberryPiPicoW.eolMenu.warp': '換行',
            'microPythonRaspberryPiPicoW.eolMenu.noWarp': '不換行',
            'microPythonRaspberryPiPicoW.category.pins': '引腳',
            'microPythonRaspberryPiPicoW.category.serial': '串列',
            'microPythonRaspberryPiPicoW.category.console': '控制台',
            'microPythonRaspberryPiPicoW.pins.setPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonRaspberryPiPicoW.pins.setDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonRaspberryPiPicoW.pins.setPwmOutput': '設定 PWM 引腳 [PIN] 輸出為 [OUT]',
            'microPythonRaspberryPiPicoW.pins.readDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonRaspberryPiPicoW.pins.readAnalogPin': '讀取類比引腳 [PIN]',
            'microPythonRaspberryPiPicoW.pins.setServoOutput': '設定伺服引腳 [PIN] 輸出為 [OUT]',
            'microPythonRaspberryPiPicoW.pins.attachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonRaspberryPiPicoW.serial.serialBegin': '串列 [NO] 初始化 鮑率 [BAUD] 接腳 RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPicoW.serial.multiSerialPrint': '串列 [NO] 印出 [VALUE] [EOL]',
            'microPythonRaspberryPiPicoW.serial.multiSerialReadALine': '串列 [NO] 讀取一行',
            'microPythonRaspberryPiPicoW.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonRaspberryPiPicoW.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
